INSERT INTO TODO (ID, DESCRIPTION, TARGET_DATE, USERNAME) VALUES (100, 'C', CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, TARGET_DATE, USERNAME) VALUES (101, 'Java', CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, TARGET_DATE, USERNAME) VALUES (102, 'Python', CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, TARGET_DATE, USERNAME) VALUES (103, 'Php', CURRENT_DATE(), 'adel')