INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (1, 'C', FALSE, CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (2, 'Java', FALSE, CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (3, 'Python', FALSE, CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (4, 'Php', FALSE, CURRENT_DATE(), 'adel')