INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (100, 'C', FALSE, CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (101, 'Java', FALSE, CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (102, 'Python', FALSE, CURRENT_DATE(), 'adel')
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (103, 'Php', FALSE, CURRENT_DATE(), 'adel')